### ISSUE TITLE
Top menu won't move back to the primary position if the system is locked while fullscreen

### ISSUE THREAD

**Issue by EPOCHvoyager** [Noobsai/fullscreen-avoider#19]
In the case of a fullscreen application that doesn't stop monitors from blanking - like a media player that only does so while media is actively playing, not while paused - the top bar will not move back to the primary monitor position after unlocking and first disengaging fullscreen mode. Manually locking the system through quick settings also engages this same behavior. Functionality isn't affected in subsequent toggling off fullscreen.

Perhaps it would be better to move the top bar back to the primary monitor, if the system is in the process of locking? Having the quick settings not be on the primary display while in the lock screen can also be a little disorienting.

Nonetheless, thank you very much for this extension - this issue is nothing but a mild inconvenience.

**Comment by Noobsai** [comment]
fixed
