### ISSUE TITLE
Cannot drag windows from second screen top panel

### ISSUE THREAD

**Issue by federico2407** [Noobsai/fullscreen-avoider#5]
I move maximised windows from one screen to the other by clicking on the top panel (instead of the title bar) and dragging the window to the other screen, that's especially handy while having a lot of tabs open with firefox, the problem is that this only works with the main screen.

**Comment by Noobsai** [comment]
Fixed in [v6](https://github.com/Noobsai/fullscreen-avoider/releases/tag/v6)
